/*
FreeRadical CMS API

Headless CMS API for FreeRadical

API version: 0.9.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package freeradical

import (
	"encoding/json"
)

// checks if the AnalyticsSummaryGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnalyticsSummaryGet200Response{}

// AnalyticsSummaryGet200Response struct for AnalyticsSummaryGet200Response
type AnalyticsSummaryGet200Response struct {
	TotalViews *int32 `json:"total_views,omitempty"`
	UniqueVisitors *int32 `json:"unique_visitors,omitempty"`
}

// NewAnalyticsSummaryGet200Response instantiates a new AnalyticsSummaryGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnalyticsSummaryGet200Response() *AnalyticsSummaryGet200Response {
	this := AnalyticsSummaryGet200Response{}
	return &this
}

// NewAnalyticsSummaryGet200ResponseWithDefaults instantiates a new AnalyticsSummaryGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnalyticsSummaryGet200ResponseWithDefaults() *AnalyticsSummaryGet200Response {
	this := AnalyticsSummaryGet200Response{}
	return &this
}

// GetTotalViews returns the TotalViews field value if set, zero value otherwise.
func (o *AnalyticsSummaryGet200Response) GetTotalViews() int32 {
	if o == nil || IsNil(o.TotalViews) {
		var ret int32
		return ret
	}
	return *o.TotalViews
}

// GetTotalViewsOk returns a tuple with the TotalViews field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalyticsSummaryGet200Response) GetTotalViewsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalViews) {
		return nil, false
	}
	return o.TotalViews, true
}

// HasTotalViews returns a boolean if a field has been set.
func (o *AnalyticsSummaryGet200Response) HasTotalViews() bool {
	if o != nil && !IsNil(o.TotalViews) {
		return true
	}

	return false
}

// SetTotalViews gets a reference to the given int32 and assigns it to the TotalViews field.
func (o *AnalyticsSummaryGet200Response) SetTotalViews(v int32) {
	o.TotalViews = &v
}

// GetUniqueVisitors returns the UniqueVisitors field value if set, zero value otherwise.
func (o *AnalyticsSummaryGet200Response) GetUniqueVisitors() int32 {
	if o == nil || IsNil(o.UniqueVisitors) {
		var ret int32
		return ret
	}
	return *o.UniqueVisitors
}

// GetUniqueVisitorsOk returns a tuple with the UniqueVisitors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalyticsSummaryGet200Response) GetUniqueVisitorsOk() (*int32, bool) {
	if o == nil || IsNil(o.UniqueVisitors) {
		return nil, false
	}
	return o.UniqueVisitors, true
}

// HasUniqueVisitors returns a boolean if a field has been set.
func (o *AnalyticsSummaryGet200Response) HasUniqueVisitors() bool {
	if o != nil && !IsNil(o.UniqueVisitors) {
		return true
	}

	return false
}

// SetUniqueVisitors gets a reference to the given int32 and assigns it to the UniqueVisitors field.
func (o *AnalyticsSummaryGet200Response) SetUniqueVisitors(v int32) {
	o.UniqueVisitors = &v
}

func (o AnalyticsSummaryGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnalyticsSummaryGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TotalViews) {
		toSerialize["total_views"] = o.TotalViews
	}
	if !IsNil(o.UniqueVisitors) {
		toSerialize["unique_visitors"] = o.UniqueVisitors
	}
	return toSerialize, nil
}

type NullableAnalyticsSummaryGet200Response struct {
	value *AnalyticsSummaryGet200Response
	isSet bool
}

func (v NullableAnalyticsSummaryGet200Response) Get() *AnalyticsSummaryGet200Response {
	return v.value
}

func (v *NullableAnalyticsSummaryGet200Response) Set(val *AnalyticsSummaryGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableAnalyticsSummaryGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableAnalyticsSummaryGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnalyticsSummaryGet200Response(val *AnalyticsSummaryGet200Response) *NullableAnalyticsSummaryGet200Response {
	return &NullableAnalyticsSummaryGet200Response{value: val, isSet: true}
}

func (v NullableAnalyticsSummaryGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnalyticsSummaryGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


