-- Add SEO fields to pages table (with existence checks)
DO $$ 
BEGIN
    ALTER TABLE pages ADD COLUMN IF NOT EXISTS meta_title VARCHAR(70) NULL;
    ALTER TABLE pages ADD COLUMN IF NOT EXISTS meta_description VARCHAR(160) NULL;
    ALTER TABLE pages ADD COLUMN IF NOT EXISTS meta_keywords VARCHAR(255) NULL;
    ALTER TABLE pages ADD COLUMN IF NOT EXISTS canonical_url VARCHAR(500) NULL;
    ALTER TABLE pages ADD COLUMN IF NOT EXISTS og_title VARCHAR(70) NULL;
    ALTER TABLE pages ADD COLUMN IF NOT EXISTS og_description VARCHAR(200) NULL;
    ALTER TABLE pages ADD COLUMN IF NOT EXISTS og_image VARCHAR(500) NULL;
    ALTER TABLE pages ADD COLUMN IF NOT EXISTS twitter_card VARCHAR(20) DEFAULT 'summary';
    ALTER TABLE pages ADD COLUMN IF NOT EXISTS twitter_title VARCHAR(70) NULL;
    ALTER TABLE pages ADD COLUMN IF NOT EXISTS twitter_description VARCHAR(200) NULL;
END $$;
